"""empty message

Revision ID: 7dea8b109ed6
Revises: b8b7d819005d
Create Date: 2024-03-10 11:51:37.697057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dea8b109ed6'
down_revision = 'b8b7d819005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
