"""empty message

Revision ID: b27a157bbdf0
Revises: db8fa5ebb690
Create Date: 2024-03-10 16:49:03.160673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27a157bbdf0'
down_revision = 'db8fa5ebb690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('filesize')
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
