"""empty message

Revision ID: b8b7d819005d
Revises: 012017778be0
Create Date: 2024-03-10 11:51:07.718755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b7d819005d'
down_revision = '012017778be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
