"""empty message

Revision ID: db8fa5ebb690
Revises: 2dacbdc97174
Create Date: 2024-03-10 16:44:56.912722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8fa5ebb690'
down_revision = '2dacbdc97174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_ref', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('photo_ref')

    # ### end Alembic commands ###
